#!/bin/bash

############ CITRIOM VM Install #############
# Version: 3.0
# Author: Jesús Maldonado

if [ $(id -u) -ne 0 ]; then
	echo "Run this script as root user only"
	exit 1
fi

MYSQL="123456"
NGINX_USER="user citriom;"
FPM_USER="user = citriom"
FPM_GROUP="group = citriom"

apt update
apt -y upgrade
apt -y install python-software-properties expect
echo | add-apt-repository ppa:ondrej/php
echo | add-apt-repository ppa:ondrej/nginx
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu xenial main'
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
apt update
apt -y upgrade

echo "mariadb-server mysql-server/root_password password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server mysql-server/root_password_again password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server-10.2 mysql-server/root_password password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server-10.2 mysql-server/root_password_again password $MYSQL" | sudo debconf-set-selections

apt -y install mariadb-server mariadb-client

SECURE_MYSQL=$(expect -c "
set timeout 10
spawn mysql_secure_installation
expect \"Enter current password for root (enter for none):\"
send \"$MYSQL\r\"
expect \"Change the root password?\"
send \"n\r\"
expect \"Remove anonymous users?\"
send \"y\r\"
expect \"Disallow root login remotely?\"
send \"y\r\"
expect \"Remove test database and access to it?\"
send \"y\r\"
expect \"Reload privilege tables now?\"
send \"y\r\"
expect eof
")
echo "$SECURE_MYSQL"
aptitude -y purge expect

apt -y install mongodb-org
apt -y install nginx curl unzip zip
ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'
ufw allow 3306/tcp
systemctl restart nginx
mkdir /etc/nginx/ssl
apt -y install curl unzip zip

apt -y install php7.2
apt -y install php-mongodb php7.2-mbstring php-mcrypt php7.2-pdo php7.2-mysql php7.2-bcmath php7.2-cli php-curl php-pear php7.2-dev php7.2-gd php7.2-zip php7.2-xml
apt -y install php7.2-fpm
sed -i "/user = www-data/c $FPM_USER" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "/group = www-data/c $FPM_GROUP" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "/user www-data;/c $NGINX_USER" /etc/nginx/nginx.conf
apt -y install beanstalkd
apt -y purge apache2

service nginx restart 
service php7.2-fpm restart
mkdir /opt/php-composer && cd /opt/php-composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
ln -s /opt/php-composer/composer.phar /usr/bin/composer
cd /home/citriom

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt -y install nodejs
npm -y install -g @angular/cli
