#!/bin/bash

############ CITRIOM VM Install #############
# Version: 5.5 (Ubuntu 18.04) ORI3
# Author: Jesús Maldonado

if [ $(id -u) -ne 0 ]; then
	echo "Run this script as root user only"
	exit 1
fi

MYSQL="123456"
NGINX_USER="user citriom;"

apt update
apt -y upgrade
apt -y install build-essential
apt -y install software-properties-common tcl expect
echo | add-apt-repository ppa:ondrej/php
echo | add-apt-repository ppa:ondrej/nginx
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
add-apt-repository 'deb [arch=amd64] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.3/ubuntu bionic main'
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
apt update
apt -y upgrade

echo "mariadb-server mysql-server/root_password password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server mysql-server/root_password_again password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server-10.3 mysql-server/root_password password $MYSQL" | sudo debconf-set-selections
echo "mariadb-server-10.3 mysql-server/root_password_again password $MYSQL" | sudo debconf-set-selections

apt -y install mariadb-server mariadb-client

SECURE_MYSQL=$(expect -c "
set timeout 10
spawn mysql_secure_installation
expect \"Enter current password for root (enter for none):\"
send \"$MYSQL\r\"
expect \"Change the root password?\"
send \"n\r\"
expect \"Remove anonymous users?\"
send \"y\r\"
expect \"Disallow root login remotely?\"
send \"y\r\"
expect \"Remove test database and access to it?\"
send \"y\r\"
expect \"Reload privilege tables now?\"
send \"y\r\"
expect eof
")
echo "$SECURE_MYSQL"
aptitude -y purge expect

apt -y install mongodb-org
service mongod start
systemctl enable mongod

apt -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'Nginx HTTPS'
ufw allow 3306/tcp
ufw allow 27017/tcp

mkdir /etc/nginx/ssl && mkdir /etc/nginx/ssl/default
openssl req -newkey rsa:2048 -nodes -keyout /etc/nginx/ssl/default/privkey.key -x509 -days 365 -out /etc/nginx/ssl/default/cert.crt -subj "/C=PR/ST=SJPR/L=PR/O=Citriom/OU=Development/CN=default"
apt -y install curl unzip zip
apt -y install memcached php7.2
apt -y install php-mongodb php7.2-pdo php7.2-mysql php7.2-bcmath php7.2-cli php7.2-dev php7.2-gd php7.2-zip php7.2-xml php-memcached
apt -y install php7.2-mbstring php-curl php7.2-fpm
sed -i "23s/.*/user = citriom/" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "24s/.*/group = citriom/" /etc/php/7.2/fpm/pool.d/www.conf
#sed -i "47s/.*/listen.owner = citriom/" /etc/php/7.2/fpm/pool.d/www.conf
#sed -i "48s/.*/listen.group = citriom/" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "/user www-data;/c $NGINX_USER" /etc/nginx/nginx.conf
sed -i "s+server_name _;+server_name _;\n\n\tssl_certificate /etc/nginx/ssl/default/cert.crt;\n\tssl_certificate_key /etc/nginx/ssl/default/privkey.key;+" /etc/nginx/sites-available/default
sed -i "s+listen 80 default_server;+#listen 80 default_server;+" /etc/nginx/sites-available/default
sed -i "/:80 default_server;/c# listen [::]:80 default_server;" /etc/nginx/sites-available/default
sed -i "s+#\slisten 443 ssl default_server;+listen 443 ssl default_server;+" /etc/nginx/sites-available/default
sed -i "/:443 ssl default_server;/c listen [::]:443 ssl default_server;" /etc/nginx/sites-available/default
sed -i "s+# Default server configuration+# HTTPS redirection\n#\n\nserver {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\tserver_name _;\n\treturn 301 https://$host$request_uri;\n}\n# Default server configuration+" /etc/nginx/sites-available/default
sed -i "s+/var/www/html;+/home/citriom/projects;+" /etc/nginx/sites-available/default
sed -i "s+index.nginx-debian.html;+index.nginx-debian.html index.php;+" /etc/nginx/sites-available/default
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
service php7.2-fpm restart
apt -y install beanstalkd supervisor
apt -y purge apache2
apt autoremove -y

apt install -y php-pear
service nginx restart

service php7.2-fpm restart

apt -y install nodejs npm && apt -y install composer
npm -y install -g @angular/cli

apt install redis -y
sed -i "147s/.*/supervised systemd/" /etc/redis/redis.conf
systemctl enable redis-server
service redis-server restart
