#!/bin/bash

############ CITRIOM VM Install #############
# Version: 2.7
# Author: Jesús Maldonado

if [ $(id -u) -ne 0 ]; then
	echo "Run this script as a Root user only" >&2
	exit 1
fi

NGINX_USER="user citriom;"
FPM_USER="user = citriom"
FPM_GROUP="group = citriom"

apt update
apt -y upgrade
apt -y install python-software-properties
echo | add-apt-repository ppa:ondrej/php
echo | add-apt-repository ppa:ondrej/nginx
apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu xenial main'
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
apt update
apt -y upgrade

apt -y install mongodb-org mariadb-server mariadb-client
mysql_secure_installation

apt -y install nginx curl unzip zip
mkdir /etc/nginx/ssl
apt -y install curl unzip zip

apt -y install php7.2
apt -y install php-mongodb php7.2-mbstring php-mcrypt php7.2-pdo php7.2-mysql php7.2-bcmath php7.2-cli php-curl php-pear php7.2-dev php7.2-gd php7.2-zip php7.2-xml
apt -y install php7.2-fpm
sed -i "/user = www-data/c $FPM_USER" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "/group = www-data/c $FPM_GROUP" /etc/php/7.2/fpm/pool.d/www.conf
sed -i "/user www-data;/c $NGINX_USER" /etc/nginx/nginx.conf
apt -y install beanstalkd
apt -y purge apache2

service nginx restart 
service php7.2-fpm restart
apt -y install composer

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt -y install nodejs
npm -y install -g @angular/cli